language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
     CODECOV_TOKEN="f4a476ec-179f-4f66-9ff0-f523b9618103"
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      aleksandr.litvinov89qw@gmail.com
    on_success: never # default: change
    on_failure: always # default: always